
import Head from "next/head";
import InstallButton from "../../components/Install/Install"
export const metadata = {
  manifest: "../../manifest.json",
  title: "Plum Finance",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="manifest" href="../../manifest.json" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add other meta tags as needed */}
      </Head>
      <body>
        {children}
        <InstallButton />
      </body>
    </html>
  );
}
