import "../../styles/globals.css";
import { Advent_Pro } from "next/font/google";
import "../../styles/globals.css";
const Advent = Advent_Pro({
  weight: "700",
  subsets: ["latin"],
 
});
export const metadata = {
  manifest:"../../manifest.json", 
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Advent.className}>{children}</body>
    </html>
  )
}
