import { Inter } from "next/font/google";
import "../globals.css";
import * as React from "react";
import Box from "@mui/material/Box";
import MuiDrawer from "@mui/material/Drawer";
import MuiAppBar, { AppBarProps as MuiAppBarProps } from "@mui/material/AppBar";
import CssBaseline from "@mui/material/CssBaseline";
import Navbar from "../../components/appbar/navBar";
import Sidebar from "../../components/sidebar/sidebar";
import { Metadata } from "next";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  manifest: "../../manifest.json",
  title: "Create Next App",
  description: "Generated by create next app",
};



// Layout.tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [open, setOpen] = React.useState(true);

  // const handleDrawerOpen = () => {
  //   setOpen(!open);
  // };
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box sx={{ display: "flex" }}>
          <CssBaseline />
          <Sidebar />
          <Box
            component="main"
            className={inter.className}
            sx={{ flexGrow: 1, height: "100vh", background: "#ffffff" }}
          >
            {/* <Navbar handleDrawerOpen={handleDrawerOpen} /> */}
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
