import { Advent_Pro } from "next/font/google";
const Advent = Advent_Pro({
  weight: "700",
  subsets: ["latin"],
 
});
import "../../styles/globals.css";
import * as React from "react";
import Box from "@mui/material/Box";
import MuiDrawer from "@mui/material/Drawer";
import MuiAppBar, { AppBarProps as MuiAppBarProps } from "@mui/material/AppBar";
import CssBaseline from "@mui/material/CssBaseline";
import Navbar from "../../components/appbar/navBar";
import Sidebar from "../../components/sidebar/sidebar";
import { Metadata } from "next";


export const metadata: Metadata = {
  manifest: "../../manifest.json",
  title: "Plum",
  description: "Generated by AI",
};

// Layout.tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const [open, setOpen] = React.useState(true);

  // const handleDrawerOpen = () => {
  //   setOpen(!open);
  // };
  return (
    <html lang="en">
      <body className={Advent.className}>
        <Box sx={{ display: "flex" }}>
          <CssBaseline />
          {/* <Sidebar /> */}
          <Box
            component="main"
            className={Advent.className}
            sx={{ flexGrow: 1, height: "100vh", background: "#ffffff" }}
          >
            <Navbar />
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
