import Head from "next/head";
import { Inter } from "next/font/google";
import InstallButton from "../../components/Install/Install"
import { Advent_Pro } from "next/font/google";
import "../../styles/globals.css";
const Advent = Advent_Pro({
  weight: "700",
  subsets: ["latin"],
 
});
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  manifest: "../../manifest.json",
  title: "Phone",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <Head>
        <link rel="manifest" href="../../manifest.json" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add other meta tags as needed */}
      </Head>
      <body className={Advent.className}>{children}</body>
    </html>
  );
}
