
import Head from "next/head";

import "../../styles/globals.css";
import { Advent_Pro } from "next/font/google";
const Advent = Advent_Pro({
  weight: "700",
  subsets: ["latin"],
 
});
export const metadata = {
  manifest: "../../manifest.json",
  title: "Plum Finance",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head>
        <link rel="manifest" href="../../manifest.json" />
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add other meta tags as needed */}
      </Head>
      <body className={Advent.className}>
        {children}
        {/* <InstallButton /> */}
      </body>
    </html>
  );
}
